axe:
  logo:
    name: "axe"
    url: "/static/images/axe-5f168d53b0.png"
    alt: "aXe"
  link: "https://github.com/dequelabs/axe-core"
ssllabs:
  logo:
    name: "ssllabs"
    url: "/static/images/qualys-ssl-labs-logo-c838cf2381.png"
    alt: "Qualys SSL Labs"
  details: true
  link: "https://www.ssllabs.com/ssltest/analyze.html?d=%URL%"
no-vulnerable-javascript-libraries:
  logo:
    name: "snyk"
    url: "/static/images/snyk-4cdfe67e79.svg"
    alt: "snyk"
  link: "https://snyk.io/vuln/"
image-optimization-cloudinary:
  logo:
    name: "cloudinary"
    url: "/static/images/cloudinary_logo_for_white_bg-64128131fa.svg"
    alt: "Cloudinary"
  details: true
  link: "https://webspeedtest.cloudinary.com"
